import { Link } from 'react-router-dom';
import styles from './IndexPage.module.scss';

const pages = [
  {
    path: '/components',
    label: 'Components',
    description: 'Primitive UI components used within posts',
  },
  {
    path: '/frames',
    label: 'Post Samples',
    description: 'Interactive block prototypes',
  },
  {
    path: '/posts',
    label: 'Autogenerated Posts',
    description: 'Sample integration post arrangements',
  },
  {
    path: '/ai-posts',
    label: 'AI Agent Posts',
    description: 'Human-in-the-loop agentic interaction samples',
  },
  {
    path: '/conversation',
    label: 'Agent Demo',
    description: 'Animated simulated conversation with an AI agent',
  },
];

export default function IndexPage() {
  return (
    <div className="page">
      <h1 className="pageHeading">Mattermost Interactive Blocks</h1>
      <nav className={styles.nav}>
        {pages.map((page) => (
          <Link key={page.path} to={page.path} className={styles.card}>
            <span className={styles.cardLabel}>{page.label}</span>
            <span className={styles.cardDescription}>{page.description}</span>
          </Link>
        ))}
      </nav>
    </div>
  );
}
