import OpenInNewIcon from '@mattermost/compass-icons/components/open-in-new';
import avatarPagerduty from '@/assets/avatar-pagerduty.png';
import avatarDatadog from '@/assets/avatar-datadog.png';
import avatarOpsgenie from '@/assets/avatar-opsgenie.png';
import avatarAws from '@/assets/avatar-aws.png';
import avatarSalesforce from '@/assets/avatar-salesforce.png';
import avatarHubspot from '@/assets/avatar-hubspot.png';
import avatarZendesk from '@/assets/avatar-zendesk.png';
import avatarAirbase from '@/assets/avatar-airbase.png';
import avatarWorkday from '@/assets/avatar-workday.png';
import avatarCoupa from '@/assets/avatar-coupa.png';
import avatarJira from '@/assets/avatar-jira.png';
import avatarEntra from '@/assets/avatar-entra.png';
import avatarOkta from '@/assets/avatar-okta.png';
import avatarServicenow from '@/assets/avatar-servicenow.png';
import avatarGithub from '@/assets/avatar-github.png';
import avatarLinear from '@/assets/avatar-linear.png';
import avatarGreenhouse from '@/assets/avatar-greenhouse.png';
import avatarStripe from '@/assets/avatar-stripe.png';
import userLukasM from '@/assets/user-lukas-meyer.png';
import userEthanB from '@/assets/user-ethan-brooks.png';
import userDanielleO from '@/assets/user-danielle-okoro.png';
import userDariusC from '@/assets/user-darius-cole.png';
import userLeilaH from '@/assets/user-leila-haddad.png';
import userMarcoR from '@/assets/user-marco-rinaldi.png';
import userLeonardR from '@/assets/user-leonard-riley.png';
import userAikoT from '@/assets/user-aiko-tan.png';
import userArjunP from '@/assets/user-arjun-patel.png';
import userIsabellaC from '@/assets/user-isabella-cruz.png';
import userDavidL from '@/assets/user-david-liang.png';
import {
  ActionBar,
  Checkbox,
  CollapsibleSection,
  Divider,
  MessageAttachment,
  Post,
  Radio,
  Select,
  SequenceItem,
  TextInput,
  TimelineItem,
  UserList,
} from '@/components';
import BackButton from '@/nav/BackButton';

function svgAvatar(text: string, bg: string, fg: string): string {
  const svg = `<svg xmlns="http://www.w3.org/2000/svg" width="32" height="32" viewBox="0 0 32 32"><rect width="32" height="32" rx="4" fill="${bg}"/><text x="16" y="21" font-family="system-ui,sans-serif" font-size="11" font-weight="700" fill="${fg}" text-anchor="middle">${text}</text></svg>`;
  return `data:image/svg+xml;charset=utf-8,${encodeURIComponent(svg)}`;
}

const avatarMassNotification = svgAvatar('MN', '#C8102E', '#FFFFFF');
const avatarEntityNetworkAlert = svgAvatar('EN', '#1A1A2E', '#C8A84B');
const avatarDataOps = svgAvatar('DO', '#16213E', '#4A9EFF');
const avatarGeospatialInsight = svgAvatar('GI', '#005B99', '#FFFFFF');
const avatarFlightTracker = svgAvatar('FT', '#003366', '#FF6B35');
const avatarMissionSystems = svgAvatar('MS', '#2D4A1E', '#A8C97F');

export default function PostsPage() {
  return (
    <div className="page">
      <BackButton />
      <h1 className="pageHeading">Autogenerated Posts</h1>

      {/* DISC-0 — Emergency mass notification */}
      <Post
        avatarSrc={avatarMassNotification}
        avatarAlt="Mass Notification System"
        username="Mass Notification System"
        timestamp="06:54 UTC"
        isBot={true}
      >
        <MessageAttachment
          header={{
            initials: 'EN',
            title: 'Emergency Notification Activated',
            subtitle: 'Critical Alert · Site: FACILITY-DELTA · 2026-0402-003',
            chip: { label: 'ACTIVATED', variant: 'danger' },
          }}
          description="Mass notification activated for facility emergency. Outreach is underway via all configured channels. Emergency conference bridge is open and accepting participants."
          metrics={[
            { value: '847', label: 'Recipients reached' },
            { value: '63%', label: 'Response rate' },
            { value: '18m', label: 'Elapsed' },
          ]}
          fields={[
            {
              label: 'Template',
              value: 'Critical Infrastructure Alert — Tier 1',
            },
            { label: 'Initiated by', value: 'Leonard Riley' },
            { label: 'Start time', value: 'April 2, 2026 · 06:54 UTC' },
            { label: 'Total recipients', value: '1,204' },
            {
              label: 'Conference bridge',
              value: '+1 (800) 555-0199 · PIN 4402#',
            },
            { label: 'Emergency line', value: '+1 (800) 555-0911' },
          ]}
          fieldColumns={2}
          actions={[
            {
              label: 'View live report',
              variant: 'primary',
              trailingIcon: <OpenInNewIcon size={16} color="currentColor" />,
            },
            { label: 'Export to Excel', variant: 'secondary' },
            { label: 'Join conference bridge', variant: 'secondary' },
          ]}
        >
          <CollapsibleSection
            title="Channel delivery"
            badge="4 channels"
            defaultOpen={false}
          >
            <TimelineItem
              title="Push notifications — 891 delivered of 1,204 sent (74%)"
              detail="Delivery complete · 06:54 UTC"
            />
            <TimelineItem
              title="SMS — 847 delivered of 1,204 sent (70%)"
              detail="Delivery complete · 06:55 UTC"
            />
            <TimelineItem
              title="Email — 1,189 delivered of 1,204 sent (99%)"
              detail="Delivery complete · 06:54 UTC"
            />
            <TimelineItem
              title="Voice calls — 634 answered, 48 missed (emergency line active)"
              detail="Outreach ongoing · started 06:55 UTC"
              isLast={true}
            />
          </CollapsibleSection>
          <CollapsibleSection
            title="Emergency response checklist"
            badge="8 tasks · 3 complete"
            defaultOpen={false}
          >
            <SequenceItem
              step={1}
              title="Activate facility emergency protocol"
              detail="Completed · Leonard Riley · 06:51 UTC"
              status="completed"
            />
            <SequenceItem
              step={2}
              title="Notify site security team"
              detail="Completed · automated · 06:52 UTC"
              status="completed"
            />
            <SequenceItem
              step={3}
              title="Initiate mass notification"
              detail="Completed · automated · 06:54 UTC"
              status="completed"
            />
            <SequenceItem
              step={4}
              title="Open emergency conference bridge"
              detail="Active · 14 participants connected"
              status="active"
            />
            <SequenceItem
              step={5}
              title="Account for all personnel"
              detail="Active · 534 of 847 confirmed"
              status="active"
            />
            <SequenceItem
              step={6}
              title="Coordinate with local authorities"
              detail="Pending"
              status="pending"
            />
            <SequenceItem
              step={7}
              title="Prepare incident report"
              detail="Pending"
              status="pending"
            />
            <SequenceItem
              step={8}
              title="Send all-clear notification"
              detail="Pending"
              status="pending"
              isLast
            />
          </CollapsibleSection>
        </MessageAttachment>
      </Post>

      {/* DISC-1 — Entity network alert */}
      <Post
        avatarSrc={avatarEntityNetworkAlert}
        avatarAlt="Entity Network Alert"
        username="Entity Network Alert"
        timestamp="06:47 UTC"
        isBot={true}
      >
        <MessageAttachment
          header={{
            initials: 'OBJ',
            title: 'OBJ-4417 · Unknown Actor',
            subtitle: 'Object Type: Person · Network Cluster 12',
            chip: { label: 'RESTRICTED', variant: 'danger' },
          }}
          description="14 new connections identified in the past 48 hours. Entity has moved into proximity with 3 previously flagged objects. Analyst review recommended."
          fields={[
            { label: 'Entity type', value: 'Person of Interest' },
            { label: 'Confidence', value: '87%' },
            { label: 'New connections', value: '14 (past 48 hrs)' },
            { label: 'Last activity', value: 'April 1, 2026 · 06:42 UTC' },
            { label: 'Assigned analyst', value: 'Unassigned', muted: true },
            { label: 'Case', value: 'CASE-2026-0312' },
          ]}
          fieldColumns={2}
          actions={[
            {
              label: 'View full details',
              variant: 'primary',
              trailingIcon: <OpenInNewIcon size={16} color="currentColor" />,
            },
            { label: 'Assign analyst', variant: 'secondary' },
            { label: 'Escalate', variant: 'danger' },
          ]}
        >
          <CollapsibleSection
            title="Connection network"
            badge="14 connections"
            defaultOpen={false}
          >
            <TimelineItem
              title="OBJ-0831 · Known associate — prior flag 2025-09"
              detail="Contact event · April 1, 2026 · 05:11 UTC"
            />
            <TimelineItem
              title="OBJ-1204 · Financial entity — shell company cluster"
              detail="Proximity match · March 30, 2026 · 22:40 UTC"
            />
            <TimelineItem
              title="OBJ-2987 · Location — monitored facility"
              detail="Geospatial correlation · March 31, 2026 · 14:23 UTC"
            />
            <TimelineItem
              title="OBJ-3340 · Communications device — IMSI flagged"
              detail="Signal intercept match · April 1, 2026 · 03:58 UTC"
              isLast={true}
            />
          </CollapsibleSection>
        </MessageAttachment>
      </Post>

      {/* DISC-2 — Pipeline build completed */}
      <Post
        avatarSrc={avatarDataOps}
        avatarAlt="DataOps"
        username="DataOps"
        timestamp="06:15 UTC"
        isBot={true}
      >
        <MessageAttachment
          title="Pipeline build completed — SIGINT Feed Ingestion"
          metrics={[
            { value: '2.4M', label: 'Records processed' },
            { value: '4m 12s', label: 'Duration' },
            { value: '99.7%', label: 'Success rate' },
          ]}
          fields={[
            { label: 'Pipeline', value: 'SIGINT Feed Ingestion v3.1' },
            { label: 'Dataset', value: '/ops/sigint/processed' },
            { label: 'Triggered by', value: 'Scheduled · 06:00 UTC' },
            { label: 'Build ID', value: 'bld-f8a2e91c' },
            { label: 'Records failed', value: '7,134' },
            { label: 'Output branch', value: 'master' },
          ]}
          fieldColumns={2}
          actions={[
            {
              label: 'View results',
              variant: 'primary',
              trailingIcon: <OpenInNewIcon size={16} color="currentColor" />,
            },
            { label: 'View lineage', variant: 'secondary' },
          ]}
        >
          <CollapsibleSection
            title="Build log"
            badge="3 warnings"
            defaultOpen={false}
          >
            <TimelineItem
              title="Source dataset snapshot acquired"
              detail="06:00:03 UTC · 2.41M records"
            />
            <TimelineItem
              title="Warning: 3 schema drift fields detected in feed-bravo"
              detail="06:02:17 UTC · auto-coerced to string"
            />
            <TimelineItem
              title="Transform complete — enrichment stage passed"
              detail="06:04:44 UTC"
            />
            <TimelineItem
              title="Output written to /ops/sigint/processed"
              detail="06:04:58 UTC · 2.39M records committed"
              isLast={true}
            />
          </CollapsibleSection>
        </MessageAttachment>
      </Post>

      {/* DISC-3 — Geospatial anomaly detected */}
      <Post
        avatarSrc={avatarGeospatialInsight}
        avatarAlt="Geospatial Insight"
        username="Geospatial Insight"
        timestamp="05:22 UTC"
        isBot={true}
      >
        <MessageAttachment
          header={{
            initials: 'SN',
            title: 'Thermal anomaly detected — Grid 38T YP 4412',
            subtitle: 'Sensor Array: ARRAY-BRAVO-07 · AO: Northern Sector',
            chip: { label: 'UNCONFIRMED', variant: 'warning' },
          }}
          metrics={[
            { value: '94%', label: 'Confidence' },
            { value: '340m', label: 'Radius' },
            { value: '12', label: 'Sensors triggered' },
          ]}
          fields={[
            { label: 'Grid reference', value: '38T YP 4412 8831' },
            { label: 'Signature type', value: 'Thermal / Vehicle' },
            { label: 'First detected', value: 'April 1, 2026 · 05:17 UTC' },
            { label: 'Priority', value: 'High' },
            { label: 'Sensor array', value: 'ARRAY-BRAVO-07' },
            { label: 'Nearest reference point', value: 'RP-CEDAR · 1.4 km NE' },
          ]}
          fieldColumns={2}
          actions={[
            { label: 'Acknowledge', variant: 'primary' },
            { label: 'Dispatch ISR asset', variant: 'secondary' },
            { label: 'Mark as false positive', variant: 'secondary' },
          ]}
        >
          <CollapsibleSection
            title="Sensor readings"
            badge="12 events"
            defaultOpen={false}
          >
            <TimelineItem
              title="Initial thermal spike — sensors B07-04, B07-05"
              detail="05:17:03 UTC · 2.1× baseline"
            />
            <TimelineItem
              title="Movement vector calculated — heading 047° at ~35 kph"
              detail="05:18:22 UTC"
            />
            <TimelineItem
              title="Correlated by sensors B07-06, B07-09, B07-11"
              detail="05:19:40 UTC · confidence raised to 94%"
            />
            <TimelineItem
              title="Signature stationary — possible stop at grid 38T YP 4415 8827"
              detail="05:21:58 UTC"
              isLast={true}
            />
          </CollapsibleSection>
        </MessageAttachment>
      </Post>

      {/* DISC-4 — Flight plan deviation */}
      <Post
        avatarSrc={avatarFlightTracker}
        avatarAlt="Flight Tracker"
        username="Flight Tracker"
        timestamp="05:41 UTC"
        isBot={true}
      >
        <MessageAttachment
          header={{
            initials: 'RC',
            title: 'RCH7714 · C-17A Globemaster III',
            subtitle: 'Route: KDOV → OJAI · AMC Charter',
            chip: { label: 'DEVIATION', variant: 'warning' },
          }}
          metrics={[
            { value: 'FL220', label: 'Current alt (filed FL350)' },
            { value: '412 kts', label: 'Ground speed' },
            { value: 'Hdg 087°', label: 'Current heading' },
          ]}
          fields={[
            { label: 'Aircraft type', value: 'C-17A Globemaster III' },
            { label: 'Registration', value: '00-0173' },
            { label: 'Origin', value: 'Dover AFB (KDOV)' },
            { label: 'Destination', value: 'Al Udeid AB (OJAI)' },
            { label: 'Deviation detected', value: 'April 1, 2026 · 05:34 UTC' },
            { label: 'Last ADS-B contact', value: 'April 1, 2026 · 05:41 UTC' },
          ]}
          fieldColumns={2}
          actions={[
            {
              label: 'Monitor flight',
              variant: 'primary',
              trailingIcon: <OpenInNewIcon size={16} color="currentColor" />,
            },
            { label: 'View full track', variant: 'secondary' },
            { label: 'Alert ATC', variant: 'danger' },
          ]}
        >
          <CollapsibleSection
            title="Track history"
            badge="8 waypoints"
            defaultOpen={false}
          >
            <TimelineItem
              title="Departed KDOV · FL280 climbing"
              detail="04:52 UTC"
            />
            <TimelineItem
              title="Reached filed FL350 — on track"
              detail="05:08 UTC"
            />
            <TimelineItem
              title="Began descent — no flight plan amendment filed"
              detail="05:21 UTC · deviation threshold crossed"
            />
            <TimelineItem
              title="Leveled at FL220 · heading 087°"
              detail="05:34 UTC · 130 nm east of last waypoint"
            />
            <TimelineItem
              title="ADS-B last received"
              detail="05:41 UTC · position 36.4°N 42.1°E"
              isLast={true}
            />
          </CollapsibleSection>
        </MessageAttachment>
      </Post>

      {/* DISC-5 — External Mission Systems: SITREP received */}
      <Post
        avatarSrc={avatarMissionSystems}
        avatarAlt="Mission Systems"
        username="Mission Systems Bot"
        timestamp="05:05 UTC"
        isBot={true}
      >
        <MessageAttachment
          header={{
            initials: 'TF',
            title: 'TF-REDHAWK · Operation IRON BRIDGE',
            subtitle: 'AO: [REDACTED] · Reporting Unit: 3rd BCT, 1st AD',
            chip: { label: 'SECRET', variant: 'danger' },
          }}
          description="Routine SITREP received via SIPRNET gateway. All elements are at assigned positions. No significant activity to report. Logistics resupply scheduled for 08:00L."
          fields={[
            { label: 'Mission ID', value: 'MSN-2026-0401-047' },
            { label: 'Status', value: 'ONGOING' },
            { label: 'Reporting unit', value: '3rd BCT, 1st Armored Division' },
            { label: 'Report type', value: 'SITREP' },
            { label: 'Submitted', value: 'April 1, 2026 · 05:00 UTC' },
            { label: 'Next update', value: 'April 1, 2026 · 11:00 UTC' },
          ]}
          fieldColumns={2}
          actions={[
            { label: 'Acknowledge', variant: 'primary' },
            { label: 'View full SITREP', variant: 'secondary' },
            { label: 'Escalate', variant: 'danger' },
          ]}
        >
          <CollapsibleSection
            title="Activity log"
            badge="5 entries"
            defaultOpen={false}
          >
            <TimelineItem
              title="SITREP #044 acknowledged — no action required"
              detail="March 31, 2026 · 23:01 UTC · Lukas Meyer"
            />
            <TimelineItem
              title="FRAGORD-12 issued — updated RoE distributed to elements"
              detail="March 31, 2026 · 18:30 UTC"
            />
            <TimelineItem
              title="Logistics convoy CONVOY-07 departed FOB ATLAS"
              detail="March 31, 2026 · 14:00 UTC · ETA 08:00L April 1"
            />
            <TimelineItem
              title="ISR asset tasked — coverage extended to northern sector"
              detail="March 31, 2026 · 11:45 UTC"
            />
            <TimelineItem
              title="Operation IRON BRIDGE initiated — all elements REDCON-1"
              detail="March 30, 2026 · 06:00 UTC"
              isLast={true}
            />
          </CollapsibleSection>
        </MessageAttachment>
      </Post>

      {/* 1 — PagerDuty: Database replication lag */}
      <Post
        avatarSrc={avatarPagerduty}
        avatarAlt="PagerDuty"
        username="PagerDuty"
        timestamp="9:14 AM"
        isBot={true}
      >
        <MessageAttachment
          title="Database replication lag — prod-db-02"
          fields={[
            { label: 'Priority', value: 'P1 – Critical' },
            { label: 'Assigned to', value: 'On-call rotation' },
            { label: 'Triggered', value: '6 minutes ago' },
          ]}
          actions={[
            { label: 'Acknowledge', variant: 'primary' },
            { label: 'Reassign', variant: 'secondary' },
            { label: 'Resolve', variant: 'secondary' },
          ]}
        >
          <CollapsibleSection
            title="Timeline"
            badge="3 events"
            defaultOpen={false}
          >
            <TimelineItem
              title="Replication lag exceeded 30s threshold"
              detail="9:08 AM PST · automated alert"
            />
            <TimelineItem
              title="Alert routed to DBA on-call"
              detail="9:09 AM · escalation policy"
            />
            <TimelineItem
              title="Acknowledged by Lukas Meyer"
              detail="9:12 AM · via mobile"
              isLast={true}
            />
          </CollapsibleSection>
        </MessageAttachment>
      </Post>

      {/* 2 — Datadog: Memory usage anomaly */}
      <Post
        avatarSrc={avatarDatadog}
        avatarAlt="Datadog"
        username="Datadog"
        timestamp="11:22 AM"
        isBot={true}
      >
        <MessageAttachment
          title="Memory usage anomaly — payments-service"
          metrics={[
            { value: '94%', label: 'Memory' },
            { value: '2.4 GB', label: 'Heap allocated' },
            { value: '3 pods', label: 'Affected' },
          ]}
          fields={[
            { label: 'Service', value: 'payments-service' },
            { label: 'Environment', value: 'production' },
            { label: 'Duration', value: '18 minutes' },
          ]}
          actions={[
            {
              label: 'View in Datadog',
              variant: 'primary',
              trailingIcon: <OpenInNewIcon size={16} color="currentColor" />,
            },
            { label: 'Snooze 30 min', variant: 'secondary' },
            { label: 'Snooze 2 hrs', variant: 'secondary' },
          ]}
        />
      </Post>

      {/* 3 — OpsGenie: On-call handoff */}
      <Post
        avatarSrc={avatarOpsgenie}
        avatarAlt="OpsGenie"
        username="OpsGenie"
        timestamp="8:00 AM"
        isBot={true}
      >
        <MessageAttachment
          title="On-call handoff — Platform Engineering"
          description="Weekly rotation started. The following engineers are on-call for Platform Engineering from Mon 8:00 AM through Sun 8:00 AM."
          actions={[
            {
              label: 'View schedule',
              variant: 'primary',
              trailingIcon: <OpenInNewIcon size={16} color="currentColor" />,
            },
          ]}
        >
          <UserList
            users={[
              {
                avatarSrc: userLukasM,
                name: 'Lukas Meyer',
                role: 'DevOps Engineer',
              },
              {
                avatarSrc: userEthanB,
                name: 'Ethan Brooks',
                role: 'Backend Engineer',
              },
              {
                avatarSrc: userDanielleO,
                name: 'Danielle Okoro',
                role: 'Software Engineer',
              },
              {
                avatarSrc: userArjunP,
                name: 'Arjun Patel',
                role: 'Platform Administrator',
              },
              {
                avatarSrc: userDavidL,
                name: 'David Liang',
                role: 'Product Manager',
              },
              {
                avatarSrc: userIsabellaC,
                name: 'Isabella Cruz',
                role: 'UX Researcher',
              },
              {
                avatarSrc: userLeonardR,
                name: 'Leonard Riley',
                role: 'Director, Security Engineering',
              },
              {
                avatarSrc: userAikoT,
                name: 'Aiko Tan',
                role: 'Senior Manager',
              },
            ]}
          />
        </MessageAttachment>
      </Post>

      {/* 4 — AWS: Budget threshold exceeded */}
      <Post
        avatarSrc={avatarAws}
        avatarAlt="AWS"
        username="AWS"
        timestamp="2:05 PM"
        isBot={true}
      >
        <MessageAttachment
          title="Cost anomaly detected — us-east-1"
          metrics={[
            { value: '$6,842', label: 'This month' },
            { value: '$4,500', label: 'Monthly budget' },
            { value: '52%', label: 'Over budget' },
          ]}
          fields={[
            { label: 'Service', value: 'Amazon EC2' },
            { label: 'Region', value: 'us-east-1' },
            { label: 'Period', value: 'March 2026' },
            { label: 'Detected', value: '2:01 PM today' },
            {
              label: 'Recommendation',
              value:
                'Anomalous EC2 spend in us-east-1 may be caused by untagged auto-scaling instances. Review instance usage and consider rightsizing or reserved instances.',
              colSpan: 2,
            },
          ]}
          fieldColumns={2}
          actions={[
            {
              label: 'View Cost Explorer',
              variant: 'primary',
              trailingIcon: <OpenInNewIcon size={16} color="currentColor" />,
            },
            { label: 'Acknowledge', variant: 'secondary' },
          ]}
        />
      </Post>

      {/* 5 — Salesforce: Deal moved to Negotiation */}
      <Post
        avatarSrc={avatarSalesforce}
        avatarAlt="Salesforce"
        username="Salesforce"
        timestamp="10:43 AM"
        isBot={true}
      >
        <MessageAttachment
          header={{
            initials: 'AP',
            title: 'Axiom Partners LLC',
            subtitle: 'Enterprise · Expansion',
          }}
          metrics={[
            { value: '$42,000', label: 'Net new ARR' },
            { value: '350', label: 'Seats' },
            { value: '2026-04-30', label: 'Close date' },
          ]}
          fields={[
            {
              label: 'Stage change',
              value:
                'Opportunity moved from Proposal/Price Quote to Negotiation/Review. Next step: legal review of MSA redlines with procurement lead.',
              colSpan: 4,
            },
            { label: 'Sales rep', value: 'Sofia Bauer' },
            { label: 'Customer engineer', value: 'Raj Patel' },
            { label: 'Account manager', value: 'Dana Mitchell' },
            { label: 'TAM', value: 'Not assigned', muted: true },
          ]}
          fieldColumns={4}
          actions={[
            {
              label: 'Open Opportunity',
              variant: 'primary',
              trailingIcon: <OpenInNewIcon size={16} color="currentColor" />,
            },
            { label: 'View account', variant: 'secondary' },
            { label: 'View contacts', variant: 'secondary' },
          ]}
        >
          <CollapsibleSection
            title="Activity notes"
            badge="4 notes"
            defaultOpen={false}
          >
            <TimelineItem
              title="Discovery call completed"
              detail="Mar 18 · Dana Mitchell noted strong alignment on security use case and out-of-band comms requirement"
            />
            <TimelineItem
              title="Technical evaluation scheduled"
              detail="Mar 21 · Mutual action plan shared with procurement lead"
            />
            <TimelineItem
              title="Legal redlines received"
              detail="Mar 26 · Procurement returned MSA with 3 redlines on data residency clauses"
            />
            <TimelineItem
              title="Moved to Negotiation/Review"
              detail="Mar 26 · Dana Mitchell · stage updated after legal review initiated"
              isLast
            />
          </CollapsibleSection>
        </MessageAttachment>
      </Post>

      {/* 6 — HubSpot: New contact created */}
      <Post
        avatarSrc={avatarHubspot}
        avatarAlt="HubSpot"
        username="HubSpot"
        timestamp="3:17 PM"
        isBot={true}
      >
        <MessageAttachment
          header={{
            initials: 'MR',
            title: 'Maya Reinholt',
            subtitle: 'VP of Engineering · Crestline Systems',
          }}
          fields={[
            { label: 'Email', value: 'm.reinholt@crestline.io' },
            { label: 'Phone', value: '+1 (415) 203-9944' },
            { label: 'Lifecycle stage', value: 'Marketing Qualified Lead' },
            { label: 'Lead source', value: 'Inbound – website' },
            { label: 'Deal owner', value: 'Sofia Bauer' },
            { label: 'Created', value: 'Today at 3:14 PM' },
          ]}
          fieldColumns={2}
          actions={[
            {
              label: 'Open in HubSpot',
              variant: 'primary',
              trailingIcon: <OpenInNewIcon size={16} color="currentColor" />,
            },
            { label: 'Enroll in sequence', variant: 'secondary' },
          ]}
        />
      </Post>

      {/* 7 — Zendesk: Support ticket opened */}
      <Post
        avatarSrc={avatarZendesk}
        avatarAlt="Zendesk"
        username="Zendesk"
        timestamp="1:48 PM"
        isBot={true}
      >
        <MessageAttachment
          header={{
            initials: 'CB',
            title: 'Chen Brands Inc.',
            subtitle: 'Premium Support · Account #48821',
          }}
          description={`"We're seeing intermittent 502 errors on the API gateway after upgrading to v4.2.1 last Friday. This is affecting roughly 20% of our automated batch jobs and we need a fix urgently."`}
          fields={[
            { label: 'Priority', value: 'Urgent' },
            { label: 'Assigned to', value: 'Unassigned', muted: true },
            { label: 'Product', value: 'API Gateway' },
            { label: 'SLA breach', value: '2 hrs 15 min' },
          ]}
        >
          <CollapsibleSection
            title="Account history"
            badge="12 tickets"
            defaultOpen={false}
          >
            <TimelineItem
              title="TKT-9201 · 502 errors on API gateway after v4.2.1 upgrade"
              detail="Mar 26, 2026 · Urgent · Open"
            />
            <TimelineItem
              title="TKT-8821 · Bulk export timeout on large datasets"
              detail="Mar 15, 2026 · High · Resolved in 4h"
            />
            <TimelineItem
              title="TKT-8604 · Auth token expiring before session timeout"
              detail="Feb 28, 2026 · Medium · Resolved in 1d"
            />
            <TimelineItem
              title="TKT-8391 · Rate limiting on automated batch operations"
              detail="Feb 10, 2026 · High · Resolved in 6h"
              isLast
            />
          </CollapsibleSection>
          <ActionBar
            select={{
              placeholder: 'Assign to agent...',
              options: [
                { value: 'aiko', label: 'Aiko Tan' },
                { value: 'arjun', label: 'Arjun Patel' },
                { value: 'leonard', label: 'Leonard Riley' },
              ],
            }}
            actions={[{ label: 'Assign', variant: 'primary' }]}
          />
        </MessageAttachment>
      </Post>

      {/* 8 — Salesforce: Quote ready for review */}
      <Post
        avatarSrc={avatarSalesforce}
        avatarAlt="Salesforce"
        username="Salesforce"
        timestamp="4:30 PM"
        isBot={true}
      >
        <MessageAttachment
          title="Quote Q-2026-0892 ready for review"
          metrics={[
            { value: '$24,750', label: 'Total value' },
            { value: '15%', label: 'Applied discount' },
            { value: 'Mar 31, 2026', label: 'Expiry date' },
          ]}
          fields={[
            { label: 'Account', value: 'Crestline Systems' },
            { label: 'Opportunity', value: 'Crestline – New Business' },
            { label: 'Prepared by', value: 'Sofia Bauer' },
            { label: 'Valid until', value: 'March 31, 2026' },
          ]}
          actions={[
            { label: 'Review & approve', variant: 'primary' },
            {
              label: 'Download PDF',
              variant: 'secondary',
              trailingIcon: <OpenInNewIcon size={16} color="currentColor" />,
            },
          ]}
        />
      </Post>

      {/* 9 — Airbase: Expense report submitted */}
      <Post
        avatarSrc={avatarAirbase}
        avatarAlt="Airbase"
        username="Airbase"
        timestamp="10:02 AM"
        isBot={true}
      >
        <MessageAttachment
          title="Expense report submitted for approval"
          description="Emma Novak submitted an expense report covering travel and accommodation for the Q1 offsite in Austin, TX. All receipts attached."
          metrics={[
            { value: '$1,847.50', label: 'Total amount' },
            { value: '9', label: 'Receipts attached' },
          ]}
          fields={[
            { label: 'Submitted by', value: 'Emma Novak' },
            { label: 'Period', value: 'Mar 10–14 2026' },
            { label: 'Cost center', value: 'Engineering' },
            { label: 'Policy compliant', value: 'Yes' },
          ]}
          actions={[
            { label: 'Approve', variant: 'success' },
            { label: 'Reject', variant: 'danger' },
            { label: 'Request changes', variant: 'secondary' },
          ]}
        />
      </Post>

      {/* 10 — Workday: PTO request */}
      <Post
        avatarSrc={avatarWorkday}
        avatarAlt="Workday"
        username="Workday"
        timestamp="9:45 AM"
        isBot={true}
      >
        <MessageAttachment
          header={{
            initials: 'DC',
            title: 'Darius Cole',
            subtitle: 'Product Designer · Design Systems',
          }}
          fields={[
            { label: 'Type', value: 'Paid Time Off' },
            { label: 'Start date', value: 'April 14, 2026' },
            { label: 'End date', value: 'April 18, 2026' },
            { label: 'Duration', value: '5 business days' },
            { label: 'Accrued balance', value: '18 days' },
            { label: 'Remaining after', value: '13 days' },
          ]}
          fieldColumns={2}
          actions={[
            { label: 'Approve', variant: 'success' },
            { label: 'Deny', variant: 'danger' },
          ]}
        >
          <CollapsibleSection
            title="Approval chain"
            badge="2 steps"
            defaultOpen={true}
          >
            <SequenceItem
              step={1}
              title="Manager approval – Leila Haddad"
              status="active"
              detail="Pending"
            />
            <SequenceItem
              step={2}
              title="HR review"
              status="pending"
              isLast={true}
            />
          </CollapsibleSection>
        </MessageAttachment>
      </Post>

      {/* 11 — Coupa: Vendor invoice pending */}
      <Post
        avatarSrc={avatarCoupa}
        avatarAlt="Coupa"
        username="Coupa"
        timestamp="11:55 AM"
        isBot={true}
      >
        <MessageAttachment
          title="Vendor invoice pending approval — INV-2026-3341"
          description="A new invoice from Veritas Cloud Services has been submitted for payment. This invoice covers infrastructure hosting services for Q1 2026 under contract MSA-2025-88."
          metrics={[
            { value: '$8,200.00', label: 'Invoice amount' },
            { value: 'Net 30', label: 'Payment terms' },
          ]}
          fields={[
            { label: 'Vendor', value: 'Veritas Cloud Services' },
            { label: 'PO number', value: 'PO-2025-1192' },
            { label: 'Submitted', value: 'March 25, 2026' },
            { label: 'Category', value: 'Cloud Infrastructure' },
          ]}
          actions={[
            { label: 'Approve', variant: 'success' },
            { label: 'Request revision', variant: 'secondary' },
          ]}
        />
      </Post>

      {/* 12 — Jira: Epic created */}
      <Post
        avatarSrc={avatarJira}
        avatarAlt="Jira"
        username="Jira"
        timestamp="2:33 PM"
        isBot={true}
      >
        <MessageAttachment
          header={{
            initials: 'DS',
            title: 'Design System – v3.0',
            subtitle: 'Project: Platform · Epic',
          }}
          description="Refactor the component library to support multi-brand theming, dark mode, and improved accessibility compliance (WCAG 2.2 AA). Estimated delivery: Q2 2026."
          fields={[
            { label: 'Assignee', value: 'Emma Novak' },
            { label: 'Priority', value: 'High' },
            { label: 'Sprint', value: 'Platform Sprint 18' },
            { label: 'Story points', value: '34' },
          ]}
          fieldColumns={2}
          actions={[
            {
              label: 'View in Jira',
              variant: 'primary',
              trailingIcon: <OpenInNewIcon size={16} color="currentColor" />,
            },
            { label: 'Assign to me', variant: 'secondary' },
          ]}
        >
          <CollapsibleSection
            title="Linked issues"
            badge="6 issues"
            defaultOpen={false}
          >
            <SequenceItem
              step={1}
              title="DS-142 · Token audit trail implementation"
              detail="Emma Novak · Completed"
              status="completed"
            />
            <SequenceItem
              step={2}
              title="DS-143 · Light/dark mode CSS variable mapping"
              detail="Emma Novak · In progress · PR open"
              status="active"
            />
            <SequenceItem
              step={3}
              title="DS-144 · Component accessibility audit (WCAG 2.2 AA)"
              detail="Darius Cole · In progress"
              status="active"
            />
            <SequenceItem
              step={4}
              title="DS-145 · Multi-brand theming configuration API"
              detail="Ethan Brooks · Not started"
              status="pending"
            />
            <SequenceItem
              step={5}
              title="DS-146 · Storybook documentation update"
              detail="Not assigned · Not started"
              status="pending"
            />
            <SequenceItem
              step={6}
              title="DS-147 · Migration guide for existing consumers"
              detail="Not assigned · Not started"
              status="pending"
              isLast
            />
          </CollapsibleSection>
        </MessageAttachment>
      </Post>

      {/* 13 — Entra: New user provisioned */}
      <Post
        avatarSrc={avatarEntra}
        avatarAlt="Entra"
        username="Entra"
        timestamp="8:30 AM"
        isBot={true}
      >
        <MessageAttachment
          header={{
            initials: 'IS',
            title: 'Isabella Cruz',
            subtitle: 'UX Researcher · Product Design',
            chip: { label: 'Active', variant: 'success' },
          }}
          fields={[
            { label: 'Email', value: 'i.cruz@company.com' },
            { label: 'Department', value: 'Product Design' },
            { label: 'Manager', value: 'Leila Haddad' },
            { label: 'Location', value: 'San Francisco, CA' },
            { label: 'Start date', value: 'March 31, 2026' },
            { label: 'License', value: 'Microsoft 365 E3' },
          ]}
          fieldColumns={2}
          actions={[
            {
              label: 'Open in Entra',
              variant: 'primary',
              trailingIcon: <OpenInNewIcon size={16} color="currentColor" />,
            },
            { label: 'Edit profile', variant: 'secondary' },
          ]}
        >
          <CollapsibleSection
            title="Groups assigned"
            badge="5 groups"
            defaultOpen={true}
          >
            <TimelineItem title="All Employees" detail="Auto-assigned" />
            <TimelineItem title="Product Design" detail="Assigned by manager" />
            <TimelineItem title="Figma – All Users" detail="Assigned by IT" />
            <TimelineItem title="Google Workspace" detail="Auto-assigned" />
            <TimelineItem
              title="VPN Access"
              detail="Assigned by IT"
              isLast={true}
            />
          </CollapsibleSection>
        </MessageAttachment>
      </Post>

      {/* 14 — Okta: Application access request */}
      <Post
        avatarSrc={avatarOkta}
        avatarAlt="Okta"
        username="Okta"
        timestamp="3:52 PM"
        isBot={true}
      >
        <MessageAttachment
          title="New application access request"
          description="Marco Rinaldi has requested access to Splunk Enterprise for security log analysis. This application requires security team approval before provisioning."
          fields={[
            { label: 'Requested by', value: 'Marco Rinaldi' },
            { label: 'Application', value: 'Splunk Enterprise' },
            {
              label: 'Justification',
              value: 'Security incident investigation workflow',
            },
            { label: 'Submitted', value: 'Today at 3:48 PM' },
          ]}
          fieldColumns={2}
          actions={[
            { label: 'Approve', variant: 'success' },
            { label: 'Deny', variant: 'danger' },
            { label: 'Request more info', variant: 'secondary' },
          ]}
        >
          <CollapsibleSection
            title="Approval chain"
            badge="3 steps"
            defaultOpen={true}
          >
            <SequenceItem
              step={1}
              title="Manager approval"
              status="completed"
            />
            <SequenceItem
              step={2}
              title="Security team review"
              detail="Pending · assigned to Leonard Riley"
              status="active"
            />
            <SequenceItem
              step={3}
              title="IT provisioning"
              status="pending"
              isLast={true}
            />
          </CollapsibleSection>
        </MessageAttachment>
      </Post>

      {/* 15 — ServiceNow: IT ticket high priority */}
      <Post
        avatarSrc={avatarServicenow}
        avatarAlt="ServiceNow"
        username="ServiceNow"
        timestamp="10:18 AM"
        isBot={true}
      >
        <MessageAttachment
          title="High priority IT ticket — INC0042891"
          description="Conference room AV system in Boardroom A is not displaying from HDMI input. Executive presentation scheduled in 90 minutes."
          metrics={[
            { value: 'P2 – High', label: 'Priority' },
            { value: '1 hr 20 min', label: 'SLA remaining' },
          ]}
          fields={[
            { label: 'Category', value: 'Hardware' },
            { label: 'Assignee', value: 'Unassigned', muted: true },
            { label: 'CI', value: 'AV-BR-A-001' },
            { label: 'Impact', value: 'Multiple users' },
          ]}
        >
          <CollapsibleSection
            title="Activity log"
            badge="2 entries"
            defaultOpen={false}
          >
            <TimelineItem
              title="Ticket created by Reception"
              detail="10:16 AM · via self-service portal"
            />
            <TimelineItem
              title="Escalated to IT Support"
              detail="10:18 AM · auto-escalation"
              isLast={true}
            />
          </CollapsibleSection>
          <ActionBar
            select={{
              placeholder: 'Assign to technician...',
              options: [
                { value: 'arjun', label: 'Arjun Patel' },
                { value: 'david', label: 'David Liang' },
                { value: 'ethan', label: 'Ethan Brooks' },
              ],
            }}
            actions={[{ label: 'Assign & notify', variant: 'primary' }]}
          />
        </MessageAttachment>
      </Post>

      {/* 16 — GitHub: PR review requested */}
      <Post
        avatarSrc={avatarGithub}
        avatarAlt="GitHub"
        username="GitHub"
        timestamp="4:05 PM"
        isBot={true}
      >
        <MessageAttachment
          header={{
            initials: 'FE',
            title: 'frontend / design-system',
            subtitle: 'Pull request #1847 · feat/token-refresh',
          }}
          description="Implements the new semantic token layer for v3.0 design system. Replaces hardcoded hex values across all components with CSS custom properties. Includes migration guide."
          fields={[
            { label: 'Author', value: 'Emma Novak' },
            { label: 'Base branch', value: 'main' },
            { label: 'Files changed', value: '47' },
            { label: 'Checks', value: '12 passing' },
          ]}
          fieldColumns={2}
          actions={[
            {
              label: 'Open PR',
              variant: 'primary',
              trailingIcon: <OpenInNewIcon size={16} color="currentColor" />,
            },
            { label: 'Approve', variant: 'success' },
            { label: 'Request changes', variant: 'secondary' },
          ]}
        >
          <UserList
            users={[
              {
                avatarSrc: userLeilaH,
                name: 'Leila Haddad',
                role: 'Engineering Manager',
              },
              {
                avatarSrc: userDariusC,
                name: 'Darius Cole',
                role: 'Product Designer',
              },
              {
                avatarSrc: userEthanB,
                name: 'Ethan Brooks',
                role: 'Backend Engineer',
              },
              {
                avatarSrc: userMarcoR,
                name: 'Marco Rinaldi',
                role: 'Security Analyst',
              },
              {
                avatarSrc: userArjunP,
                name: 'Arjun Patel',
                role: 'Platform Administrator',
              },
            ]}
          />
        </MessageAttachment>
      </Post>

      {/* 17 — Linear: Sprint standup summary */}
      <Post
        avatarSrc={avatarLinear}
        avatarAlt="Linear"
        username="Linear"
        timestamp="9:00 AM"
        isBot={true}
      >
        <MessageAttachment
          title="Sprint 52 — standup summary"
          description="Automated standup digest for Platform Engineering. 4 active issues across 3 engineers."
          actions={[
            {
              label: 'View sprint',
              variant: 'primary',
              trailingIcon: <OpenInNewIcon size={16} color="currentColor" />,
            },
          ]}
        >
          <CollapsibleSection
            title="Issue status"
            badge="8 issues"
            defaultOpen={true}
          >
            <SequenceItem
              step={1}
              title="Token refresh endpoint — Ethan Brooks"
              detail="Completed yesterday"
              status="completed"
            />
            <SequenceItem
              step={2}
              title="Design system token migration — Emma Novak"
              detail="In progress · PR open"
              status="active"
            />
            <SequenceItem
              step={3}
              title="CI pipeline cache optimisation — Lukas Meyer"
              detail="In progress · blocked on infra access"
              status="active"
            />
            <SequenceItem
              step={4}
              title="API rate limiting — Danielle Okoro"
              detail="Pending · starts tomorrow"
              status="pending"
              isLast={true}
            />
          </CollapsibleSection>
        </MessageAttachment>
      </Post>

      {/* 18 — Security: Suspicious login activity */}
      <Post
        avatarSrc={avatarPagerduty}
        avatarAlt="Security"
        username="Security"
        timestamp="7:14 AM"
        isBot={true}
      >
        <MessageAttachment
          title="Suspicious login activity detected"
          description="Multiple failed authentication attempts have been detected against a privileged account. Geographic anomaly: attempts originating from three different countries within a 12-minute window."
          metrics={[
            { value: '47', label: 'Failed attempts' },
            { value: '3', label: 'Source IPs' },
            { value: '2', label: 'Accounts targeted' },
          ]}
          fields={[
            { label: 'Target account', value: 'leonard.riley@company.com' },
            {
              label: 'Source IPs',
              value: '185.220.x.x · 91.108.x.x · 198.44.x.x',
            },
            { label: 'Location', value: 'Russia · Netherlands · Brazil' },
            { label: 'Time window', value: '7:01 AM – 7:13 AM' },
            {
              label: 'Recommended action',
              value:
                'Immediately suspend affected accounts and rotate credentials. Block identified IP ranges at the firewall level. Initiate incident review with the security team.',
              colSpan: 2,
            },
          ]}
          fieldColumns={2}
          actions={[
            { label: 'Suspend accounts', variant: 'danger' },
            { label: 'Block IPs', variant: 'danger' },
            {
              label: 'View audit log',
              variant: 'secondary',
              trailingIcon: <OpenInNewIcon size={16} color="currentColor" />,
            },
          ]}
        />
      </Post>

      {/* 19 — Greenhouse: New candidate in pipeline */}
      <Post
        avatarSrc={avatarGreenhouse}
        avatarAlt="Greenhouse"
        username="Greenhouse"
        timestamp="2:20 PM"
        isBot={true}
      >
        <MessageAttachment
          header={{
            initials: 'TW',
            title: 'Taylor Westbrook',
            subtitle: 'Senior Frontend Engineer · Engineering',
          }}
          fields={[
            { label: 'Stage', value: 'Technical interview' },
            { label: 'Applied', value: 'March 24, 2026' },
            { label: 'Source', value: 'LinkedIn Recruiter' },
            { label: 'Recruiter', value: 'Aiko Tan' },
            { label: 'Coordinator', value: 'Sofia Bauer' },
            { label: 'Interview panel', value: 'Emma Novak · Ethan Brooks' },
          ]}
          fieldColumns={2}
          actions={[
            {
              label: 'Open in Greenhouse',
              variant: 'primary',
              trailingIcon: <OpenInNewIcon size={16} color="currentColor" />,
            },
            { label: 'Schedule next interview', variant: 'secondary' },
          ]}
        >
          <CollapsibleSection
            title="Interview scorecard"
            badge="2 submitted"
            defaultOpen={false}
          >
            <TimelineItem
              title="Leila Haddad · Engineering Manager · Strong Yes"
              detail="Exceptional systems thinking and clear communication. Would thrive in a cross-functional role."
            />
            <TimelineItem
              title="Ethan Brooks · Backend Engineer · Yes"
              detail="Solid frontend fundamentals, good grasp of performance trade-offs. Minor gaps in TypeScript generics."
              isLast
            />
          </CollapsibleSection>
        </MessageAttachment>
      </Post>

      {/* 20 — Stripe: Payment failed */}
      <Post
        avatarSrc={avatarStripe}
        avatarAlt="Stripe"
        username="Stripe"
        timestamp="5:38 PM"
        isBot={true}
      >
        <MessageAttachment
          header={{
            initials: 'VC',
            title: 'Veloz Consulting Group',
            subtitle: 'Enterprise Plan · Monthly billing',
            chip: { label: 'Payment failed' },
          }}
          description="Automatic renewal charge for the Enterprise Plan failed. The card on file was declined by the issuing bank. This is the second consecutive failed attempt."
          metrics={[
            { value: '$3,499.00', label: 'Amount due' },
            { value: '2', label: 'Failed attempts' },
          ]}
          fields={[
            { label: 'Customer', value: 'Veloz Consulting Group' },
            { label: 'Payment method', value: 'Visa ···· 4821' },
            { label: 'Error code', value: 'card_declined' },
            { label: 'Last attempt', value: 'Today at 5:36 PM' },
          ]}
          fieldColumns={2}
          actions={[
            { label: 'Retry payment', variant: 'primary' },
            { label: 'Contact customer', variant: 'secondary' },
            {
              label: 'Open in Stripe',
              variant: 'secondary',
              trailingIcon: <OpenInNewIcon size={16} color="currentColor" />,
            },
          ]}
        />
      </Post>

      {/* 21 — PagerDuty: Manually trigger incident */}
      <Post
        avatarSrc={avatarPagerduty}
        avatarAlt="PagerDuty"
        username="PagerDuty"
        timestamp="9:12 AM"
        isBot={true}
      >
        <MessageAttachment title="Trigger a manual incident">
          <TextInput
            label="Incident title"
            placeholder="Brief description of the issue"
          />
          <Select
            label="Affected service"
            placeholder="Select a service"
            options={[
              { value: 'api-gateway', label: 'API Gateway' },
              { value: 'payments-service', label: 'Payments Service' },
              { value: 'auth-service', label: 'Auth Service' },
              { value: 'data-pipeline', label: 'Data Pipeline' },
            ]}
          />
          <div>
            <p
              style={{
                fontSize: 12,
                fontWeight: 600,
                color: 'var(--center-channel-color)',
                marginBottom: 8,
              }}
            >
              Urgency
            </p>
            <div style={{ display: 'flex', gap: 16 }}>
              <Radio name="incident-urgency" defaultChecked>
                High
              </Radio>
              <Radio name="incident-urgency">Low</Radio>
            </div>
          </div>
          <Divider />
          <ActionBar
            actions={[
              { label: 'Trigger incident', variant: 'danger' },
              { label: 'Cancel', variant: 'secondary' },
            ]}
          />
        </MessageAttachment>
      </Post>

      {/* 22 — Jira: Create issue */}
      <Post
        avatarSrc={avatarJira}
        avatarAlt="Jira"
        username="Jira"
        timestamp="11:30 AM"
        isBot={true}
      >
        <MessageAttachment title="Create a Jira issue">
          <Select
            label="Project"
            placeholder="Select a project"
            options={[
              { value: 'platform', label: 'Platform Engineering' },
              { value: 'design-system', label: 'Design System' },
              { value: 'security', label: 'Security' },
              { value: 'growth', label: 'Growth' },
            ]}
          />
          <div
            style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: 8 }}
          >
            <Select
              label="Issue type"
              placeholder="Select type"
              options={[
                { value: 'bug', label: 'Bug' },
                { value: 'story', label: 'Story' },
                { value: 'task', label: 'Task' },
                { value: 'epic', label: 'Epic' },
              ]}
            />
            <Select
              label="Priority"
              placeholder="Select priority"
              options={[
                { value: 'highest', label: 'Highest' },
                { value: 'high', label: 'High' },
                { value: 'medium', label: 'Medium' },
                { value: 'low', label: 'Low' },
              ]}
            />
          </div>
          <TextInput label="Summary" placeholder="Short summary of the issue" />
          <Select
            label="Assignee"
            placeholder="Unassigned"
            options={[
              { value: 'emma', label: 'Emma Novak' },
              { value: 'ethan', label: 'Ethan Brooks' },
              { value: 'danielle', label: 'Danielle Okoro' },
              { value: 'lukas', label: 'Lukas Meyer' },
            ]}
          />
          <Checkbox>Notify assignee by email</Checkbox>
          <Divider />
          <ActionBar
            actions={[
              { label: 'Create issue', variant: 'primary' },
              { label: 'Cancel', variant: 'secondary' },
            ]}
          />
        </MessageAttachment>
      </Post>

      {/* 23 — Workday: Submit expense */}
      <Post
        avatarSrc={avatarWorkday}
        avatarAlt="Workday"
        username="Workday"
        timestamp="3:45 PM"
        isBot={true}
      >
        <MessageAttachment title="Submit an expense">
          <div
            style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: 8 }}
          >
            <TextInput
              label="Merchant"
              placeholder="e.g. Marriott San Francisco"
            />
            <TextInput label="Amount (USD)" placeholder="0.00" />
          </div>
          <Select
            label="Category"
            placeholder="Select a category"
            options={[
              { value: 'travel', label: 'Travel' },
              { value: 'meals', label: 'Meals & Entertainment' },
              { value: 'software', label: 'Software & Subscriptions' },
              { value: 'office', label: 'Office Supplies' },
              { value: 'other', label: 'Other' },
            ]}
          />
          <TextInput
            label="Notes"
            placeholder="Optional description or context"
          />
          <Divider />
          <ActionBar
            actions={[
              { label: 'Submit expense', variant: 'primary' },
              { label: 'Save draft', variant: 'secondary' },
            ]}
          />
        </MessageAttachment>
      </Post>
    </div>
  );
}
