import OpenInNewIcon from '@mattermost/compass-icons/components/open-in-new';
import avatarPagerduty from '../assets/avatar-pagerduty.png';
import avatarDatadog from '../assets/avatar-datadog.png';
import avatarOpsgenie from '../assets/avatar-opsgenie.png';
import avatarAws from '../assets/avatar-aws.png';
import avatarSalesforce from '../assets/avatar-salesforce.png';
import avatarHubspot from '../assets/avatar-hubspot.png';
import avatarZendesk from '../assets/avatar-zendesk.png';
import avatarAirbase from '../assets/avatar-airbase.png';
import avatarWorkday from '../assets/avatar-workday.png';
import avatarCoupa from '../assets/avatar-coupa.png';
import avatarJira from '../assets/avatar-jira.png';
import avatarEntra from '../assets/avatar-entra.png';
import avatarOkta from '../assets/avatar-okta.png';
import avatarServicenow from '../assets/avatar-servicenow.png';
import avatarGithub from '../assets/avatar-github.png';
import avatarLinear from '../assets/avatar-linear.png';
import avatarGreenhouse from '../assets/avatar-greenhouse.png';
import avatarStripe from '../assets/avatar-stripe.png';
import userLukasM from '../assets/user-lukas-meyer.png';
import userEthanB from '../assets/user-ethan-brooks.png';
import userDanielleO from '../assets/user-danielle-okoro.png';
import userEmmaN from '../assets/user-emma-novak.png';
import userDariusC from '../assets/user-darius-cole.png';
import userLeilaH from '../assets/user-leila-haddad.png';
import userMarcoR from '../assets/user-marco-rinaldi.png';
import userLeonardR from '../assets/user-leonard-riley.png';
import userAikoT from '../assets/user-aiko-tan.png';
import userArjunP from '../assets/user-arjun-patel.png';
import userIsabellaC from '../assets/user-isabella-cruz.png';
import userDavidL from '../assets/user-david-liang.png';
import Post from '../components/Post/Post';
import MessageAttachment from '../components/MessageAttachment/MessageAttachment';
import CollapsibleSection from '../components/CollapsibleSection/CollapsibleSection';
import TimelineItem from '../components/TimelineItem/TimelineItem';
import SequenceItem from '../components/SequenceItem/SequenceItem';
import UserList from '../components/UserList/UserList';
import ActionBar from '../components/ActionBar/ActionBar';
import TextInput from '../components/TextInput/TextInput';
import Select from '../components/Select/Select';
import Radio from '../components/Radio/Radio';
import Checkbox from '../components/Checkbox/Checkbox';
import Switch from '../components/Switch/Switch';
import Divider from '../components/Divider/Divider';
import BackButton from '../nav/BackButton';
import styles from './FramesPage.module.scss';

export default function PostsPage() {
  return (
    <div className={styles.page}>
      <BackButton />
      <h1 className={styles.heading}>Autogenerated Posts</h1>

      {/* 1 — PagerDuty: Database replication lag */}
      <Post
        avatarSrc={avatarPagerduty}
        avatarAlt="PagerDuty"
        username="PagerDuty"
        timestamp="9:14 AM"
        isBot={true}
      >
        <MessageAttachment
          title="Database replication lag — prod-db-02"
          fields={[
            { label: 'Priority', value: 'P1 – Critical' },
            { label: 'Assigned to', value: 'On-call rotation' },
            { label: 'Triggered', value: '6 minutes ago' },
          ]}
          actions={[
            { label: 'Acknowledge', variant: 'primary' },
            { label: 'Reassign', variant: 'secondary' },
            { label: 'Resolve', variant: 'secondary' },
          ]}
        >
          <CollapsibleSection title="Timeline" badge="3 events" defaultOpen={false}>
            <TimelineItem title="Replication lag exceeded 30s threshold" detail="9:08 AM PST · automated alert" />
            <TimelineItem title="Alert routed to DBA on-call" detail="9:09 AM · escalation policy" />
            <TimelineItem title="Acknowledged by Lukas Meyer" detail="9:12 AM · via mobile" isLast={true} />
          </CollapsibleSection>
        </MessageAttachment>
      </Post>

      {/* 2 — Datadog: Memory usage anomaly */}
      <Post
        avatarSrc={avatarDatadog}
        avatarAlt="Datadog"
        username="Datadog"
        timestamp="11:22 AM"
        isBot={true}
      >
        <MessageAttachment
          title="Memory usage anomaly — payments-service"
          metrics={[
            { value: '94%', label: 'Memory' },
            { value: '2.4 GB', label: 'Heap allocated' },
            { value: '3 pods', label: 'Affected' },
          ]}
          fields={[
            { label: 'Service', value: 'payments-service' },
            { label: 'Environment', value: 'production' },
            { label: 'Duration', value: '18 minutes' },
          ]}
          actions={[
            {
              label: 'View in Datadog',
              variant: 'primary',
              trailingIcon: <OpenInNewIcon size={16} color="currentColor" />,
            },
            { label: 'Snooze 30 min', variant: 'secondary' },
            { label: 'Snooze 2 hrs', variant: 'secondary' },
          ]}
        />
      </Post>

      {/* 3 — OpsGenie: On-call handoff */}
      <Post
        avatarSrc={avatarOpsgenie}
        avatarAlt="OpsGenie"
        username="OpsGenie"
        timestamp="8:00 AM"
        isBot={true}
      >
        <MessageAttachment
          title="On-call handoff — Platform Engineering"
          description="Weekly rotation started. The following engineers are on-call for Platform Engineering from Mon 8:00 AM through Sun 8:00 AM."
          actions={[
            {
              label: 'View schedule',
              variant: 'primary',
              trailingIcon: <OpenInNewIcon size={16} color="currentColor" />,
            },
          ]}
        >
          <UserList
            users={[
              { avatarSrc: userLukasM, name: 'Lukas Meyer', role: 'DevOps Engineer' },
              { avatarSrc: userEthanB, name: 'Ethan Brooks', role: 'Backend Engineer' },
              { avatarSrc: userDanielleO, name: 'Danielle Okoro', role: 'Software Engineer' },
              { avatarSrc: userArjunP, name: 'Arjun Patel', role: 'Platform Administrator' },
              { avatarSrc: userDavidL, name: 'David Liang', role: 'Product Manager' },
              { avatarSrc: userIsabellaC, name: 'Isabella Cruz', role: 'UX Researcher' },
              { avatarSrc: userLeonardR, name: 'Leonard Riley', role: 'Director, Security Engineering' },
              { avatarSrc: userAikoT, name: 'Aiko Tan', role: 'Senior Manager' },
            ]}
          />
        </MessageAttachment>
      </Post>

      {/* 4 — AWS: Budget threshold exceeded */}
      <Post
        avatarSrc={avatarAws}
        avatarAlt="AWS"
        username="AWS"
        timestamp="2:05 PM"
        isBot={true}
      >
        <MessageAttachment
          title="Cost anomaly detected — us-east-1"
          metrics={[
            { value: '$6,842', label: 'This month' },
            { value: '$4,500', label: 'Monthly budget' },
            { value: '52%', label: 'Over budget' },
          ]}
          fields={[
            { label: 'Service', value: 'Amazon EC2' },
            { label: 'Region', value: 'us-east-1' },
            { label: 'Period', value: 'March 2026' },
            { label: 'Detected', value: '2:01 PM today' },
            { label: 'Recommendation', value: 'Anomalous EC2 spend in us-east-1 may be caused by untagged auto-scaling instances. Review instance usage and consider rightsizing or reserved instances.', colSpan: 2 },
          ]}
          fieldColumns={2}
          actions={[
            {
              label: 'View Cost Explorer',
              variant: 'primary',
              trailingIcon: <OpenInNewIcon size={16} color="currentColor" />,
            },
            { label: 'Acknowledge', variant: 'secondary' },
          ]}
        />
      </Post>

      {/* 5 — Salesforce: Deal moved to Negotiation */}
      <Post
        avatarSrc={avatarSalesforce}
        avatarAlt="Salesforce"
        username="Salesforce"
        timestamp="10:43 AM"
        isBot={true}
      >
        <MessageAttachment
          header={{ initials: 'AP', title: 'Axiom Partners LLC', subtitle: 'Enterprise · Expansion' }}
          metrics={[
            { value: '$42,000', label: 'Net new ARR' },
            { value: '350', label: 'Seats' },
            { value: '2026-04-30', label: 'Close date' },
          ]}
          fields={[
            { label: 'Stage change', value: 'Opportunity moved from Proposal/Price Quote to Negotiation/Review. Next step: legal review of MSA redlines with procurement lead.', colSpan: 4 },
            { label: 'Sales rep', value: 'Sofia Bauer' },
            { label: 'Customer engineer', value: 'Raj Patel' },
            { label: 'Account manager', value: 'Dana Mitchell' },
            { label: 'TAM', value: 'Not assigned', muted: true },
          ]}
          fieldColumns={4}
          actions={[
            {
              label: 'Open Opportunity',
              variant: 'primary',
              trailingIcon: <OpenInNewIcon size={16} color="currentColor" />,
            },
            { label: 'View account', variant: 'secondary' },
            { label: 'View contacts', variant: 'secondary' },
          ]}
        >
          <CollapsibleSection title="Activity notes" badge="4 notes" defaultOpen={false}>
            <TimelineItem title="Discovery call completed" detail="Mar 18 · Dana Mitchell noted strong alignment on security use case and out-of-band comms requirement" />
            <TimelineItem title="Technical evaluation scheduled" detail="Mar 21 · Mutual action plan shared with procurement lead" />
            <TimelineItem title="Legal redlines received" detail="Mar 26 · Procurement returned MSA with 3 redlines on data residency clauses" />
            <TimelineItem title="Moved to Negotiation/Review" detail="Mar 26 · Dana Mitchell · stage updated after legal review initiated" isLast />
          </CollapsibleSection>
        </MessageAttachment>
      </Post>

      {/* 6 — HubSpot: New contact created */}
      <Post
        avatarSrc={avatarHubspot}
        avatarAlt="HubSpot"
        username="HubSpot"
        timestamp="3:17 PM"
        isBot={true}
      >
        <MessageAttachment
          header={{ initials: 'MR', title: 'Maya Reinholt', subtitle: 'VP of Engineering · Crestline Systems' }}
          fields={[
            { label: 'Email', value: 'm.reinholt@crestline.io' },
            { label: 'Phone', value: '+1 (415) 203-9944' },
            { label: 'Lifecycle stage', value: 'Marketing Qualified Lead' },
            { label: 'Lead source', value: 'Inbound – website' },
            { label: 'Deal owner', value: 'Sofia Bauer' },
            { label: 'Created', value: 'Today at 3:14 PM' },
          ]}
          fieldColumns={2}
          actions={[
            {
              label: 'Open in HubSpot',
              variant: 'primary',
              trailingIcon: <OpenInNewIcon size={16} color="currentColor" />,
            },
            { label: 'Enroll in sequence', variant: 'secondary' },
          ]}
        />
      </Post>

      {/* 7 — Zendesk: Support ticket opened */}
      <Post
        avatarSrc={avatarZendesk}
        avatarAlt="Zendesk"
        username="Zendesk"
        timestamp="1:48 PM"
        isBot={true}
      >
        <MessageAttachment
          header={{ initials: 'CB', title: 'Chen Brands Inc.', subtitle: 'Premium Support · Account #48821' }}
          description={`"We're seeing intermittent 502 errors on the API gateway after upgrading to v4.2.1 last Friday. This is affecting roughly 20% of our automated batch jobs and we need a fix urgently."`}
          fields={[
            { label: 'Priority', value: 'Urgent' },
            { label: 'Assigned to', value: 'Unassigned', muted: true },
            { label: 'Product', value: 'API Gateway' },
            { label: 'SLA breach', value: '2 hrs 15 min' },
          ]}
        >
          <CollapsibleSection title="Account history" badge="12 tickets" defaultOpen={false}>
            <TimelineItem title="TKT-9201 · 502 errors on API gateway after v4.2.1 upgrade" detail="Mar 26, 2026 · Urgent · Open" />
            <TimelineItem title="TKT-8821 · Bulk export timeout on large datasets" detail="Mar 15, 2026 · High · Resolved in 4h" />
            <TimelineItem title="TKT-8604 · Auth token expiring before session timeout" detail="Feb 28, 2026 · Medium · Resolved in 1d" />
            <TimelineItem title="TKT-8391 · Rate limiting on automated batch operations" detail="Feb 10, 2026 · High · Resolved in 6h" isLast />
          </CollapsibleSection>
          <ActionBar
            select={{
              placeholder: 'Assign to agent...',
              options: [
                { value: 'aiko', label: 'Aiko Tan' },
                { value: 'arjun', label: 'Arjun Patel' },
                { value: 'leonard', label: 'Leonard Riley' },
              ],
            }}
            actions={[{ label: 'Assign', variant: 'primary' }]}
          />
        </MessageAttachment>
      </Post>

      {/* 8 — Salesforce: Quote ready for review */}
      <Post
        avatarSrc={avatarSalesforce}
        avatarAlt="Salesforce"
        username="Salesforce"
        timestamp="4:30 PM"
        isBot={true}
      >
        <MessageAttachment
          title="Quote Q-2026-0892 ready for review"
          metrics={[
            { value: '$24,750', label: 'Total value' },
            { value: '15%', label: 'Applied discount' },
            { value: 'Mar 31, 2026', label: 'Expiry date' },
          ]}
          fields={[
            { label: 'Account', value: 'Crestline Systems' },
            { label: 'Opportunity', value: 'Crestline – New Business' },
            { label: 'Prepared by', value: 'Sofia Bauer' },
            { label: 'Valid until', value: 'March 31, 2026' },
          ]}
          actions={[
            { label: 'Review & approve', variant: 'primary' },
            {
              label: 'Download PDF',
              variant: 'secondary',
              trailingIcon: <OpenInNewIcon size={16} color="currentColor" />,
            },
          ]}
        />
      </Post>

      {/* 9 — Airbase: Expense report submitted */}
      <Post
        avatarSrc={avatarAirbase}
        avatarAlt="Airbase"
        username="Airbase"
        timestamp="10:02 AM"
        isBot={true}
      >
        <MessageAttachment
          title="Expense report submitted for approval"
          description="Emma Novak submitted an expense report covering travel and accommodation for the Q1 offsite in Austin, TX. All receipts attached."
          metrics={[
            { value: '$1,847.50', label: 'Total amount' },
            { value: '9', label: 'Receipts attached' },
          ]}
          fields={[
            { label: 'Submitted by', value: 'Emma Novak' },
            { label: 'Period', value: 'Mar 10–14 2026' },
            { label: 'Cost center', value: 'Engineering' },
            { label: 'Policy compliant', value: 'Yes' },
          ]}
          actions={[
            { label: 'Approve', variant: 'success' },
            { label: 'Reject', variant: 'danger' },
            { label: 'Request changes', variant: 'secondary' },
          ]}
        />
      </Post>

      {/* 10 — Workday: PTO request */}
      <Post
        avatarSrc={avatarWorkday}
        avatarAlt="Workday"
        username="Workday"
        timestamp="9:45 AM"
        isBot={true}
      >
        <MessageAttachment
          header={{ initials: 'DC', title: 'Darius Cole', subtitle: 'Product Designer · Design Systems' }}
          fields={[
            { label: 'Type', value: 'Paid Time Off' },
            { label: 'Start date', value: 'April 14, 2026' },
            { label: 'End date', value: 'April 18, 2026' },
            { label: 'Duration', value: '5 business days' },
            { label: 'Accrued balance', value: '18 days' },
            { label: 'Remaining after', value: '13 days' },
          ]}
          fieldColumns={2}
          actions={[
            { label: 'Approve', variant: 'success' },
            { label: 'Deny', variant: 'danger' },
          ]}
        >
          <CollapsibleSection title="Approval chain" badge="2 steps" defaultOpen={true}>
            <SequenceItem step={1} title="Manager approval – Leila Haddad" status="active" detail="Pending" />
            <SequenceItem step={2} title="HR review" status="pending" isLast={true} />
          </CollapsibleSection>
        </MessageAttachment>
      </Post>

      {/* 11 — Coupa: Vendor invoice pending */}
      <Post
        avatarSrc={avatarCoupa}
        avatarAlt="Coupa"
        username="Coupa"
        timestamp="11:55 AM"
        isBot={true}
      >
        <MessageAttachment
          title="Vendor invoice pending approval — INV-2026-3341"
          description="A new invoice from Veritas Cloud Services has been submitted for payment. This invoice covers infrastructure hosting services for Q1 2026 under contract MSA-2025-88."
          metrics={[
            { value: '$8,200.00', label: 'Invoice amount' },
            { value: 'Net 30', label: 'Payment terms' },
          ]}
          fields={[
            { label: 'Vendor', value: 'Veritas Cloud Services' },
            { label: 'PO number', value: 'PO-2025-1192' },
            { label: 'Submitted', value: 'March 25, 2026' },
            { label: 'Category', value: 'Cloud Infrastructure' },
          ]}
          actions={[
            { label: 'Approve', variant: 'success' },
            { label: 'Request revision', variant: 'secondary' },
          ]}
        />
      </Post>

      {/* 12 — Jira: Epic created */}
      <Post
        avatarSrc={avatarJira}
        avatarAlt="Jira"
        username="Jira"
        timestamp="2:33 PM"
        isBot={true}
      >
        <MessageAttachment
          header={{ initials: 'DS', title: 'Design System – v3.0', subtitle: 'Project: Platform · Epic' }}
          description="Refactor the component library to support multi-brand theming, dark mode, and improved accessibility compliance (WCAG 2.2 AA). Estimated delivery: Q2 2026."
          fields={[
            { label: 'Assignee', value: 'Emma Novak' },
            { label: 'Priority', value: 'High' },
            { label: 'Sprint', value: 'Platform Sprint 18' },
            { label: 'Story points', value: '34' },
          ]}
          fieldColumns={2}
          actions={[
            {
              label: 'View in Jira',
              variant: 'primary',
              trailingIcon: <OpenInNewIcon size={16} color="currentColor" />,
            },
            { label: 'Assign to me', variant: 'secondary' },
          ]}
        >
          <CollapsibleSection title="Linked issues" badge="6 issues" defaultOpen={false}>
            <SequenceItem step={1} title="DS-142 · Token audit trail implementation" detail="Emma Novak · Completed" status="completed" />
            <SequenceItem step={2} title="DS-143 · Light/dark mode CSS variable mapping" detail="Emma Novak · In progress · PR open" status="active" />
            <SequenceItem step={3} title="DS-144 · Component accessibility audit (WCAG 2.2 AA)" detail="Darius Cole · In progress" status="active" />
            <SequenceItem step={4} title="DS-145 · Multi-brand theming configuration API" detail="Ethan Brooks · Not started" status="pending" />
            <SequenceItem step={5} title="DS-146 · Storybook documentation update" detail="Not assigned · Not started" status="pending" />
            <SequenceItem step={6} title="DS-147 · Migration guide for existing consumers" detail="Not assigned · Not started" status="pending" isLast />
          </CollapsibleSection>
        </MessageAttachment>
      </Post>

      {/* 13 — Entra: New user provisioned */}
      <Post
        avatarSrc={avatarEntra}
        avatarAlt="Entra"
        username="Entra"
        timestamp="8:30 AM"
        isBot={true}
      >
        <MessageAttachment
          header={{
            initials: 'IS',
            title: 'Isabella Cruz',
            subtitle: 'UX Researcher · Product Design',
            chip: { label: 'Active', variant: 'success' },
          }}
          fields={[
            { label: 'Email', value: 'i.cruz@company.com' },
            { label: 'Department', value: 'Product Design' },
            { label: 'Manager', value: 'Leila Haddad' },
            { label: 'Location', value: 'San Francisco, CA' },
            { label: 'Start date', value: 'March 31, 2026' },
            { label: 'License', value: 'Microsoft 365 E3' },
          ]}
          fieldColumns={2}
          actions={[
            {
              label: 'Open in Entra',
              variant: 'primary',
              trailingIcon: <OpenInNewIcon size={16} color="currentColor" />,
            },
            { label: 'Edit profile', variant: 'secondary' },
          ]}
        >
          <CollapsibleSection title="Groups assigned" badge="5 groups" defaultOpen={true}>
            <TimelineItem title="All Employees" detail="Auto-assigned" />
            <TimelineItem title="Product Design" detail="Assigned by manager" />
            <TimelineItem title="Figma – All Users" detail="Assigned by IT" />
            <TimelineItem title="Google Workspace" detail="Auto-assigned" />
            <TimelineItem title="VPN Access" detail="Assigned by IT" isLast={true} />
          </CollapsibleSection>
        </MessageAttachment>
      </Post>

      {/* 14 — Okta: Application access request */}
      <Post
        avatarSrc={avatarOkta}
        avatarAlt="Okta"
        username="Okta"
        timestamp="3:52 PM"
        isBot={true}
      >
        <MessageAttachment
          title="New application access request"
          description="Marco Rinaldi has requested access to Splunk Enterprise for security log analysis. This application requires security team approval before provisioning."
          fields={[
            { label: 'Requested by', value: 'Marco Rinaldi' },
            { label: 'Application', value: 'Splunk Enterprise' },
            { label: 'Justification', value: 'Security incident investigation workflow' },
            { label: 'Submitted', value: 'Today at 3:48 PM' },
          ]}
          fieldColumns={2}
          actions={[
            { label: 'Approve', variant: 'success' },
            { label: 'Deny', variant: 'danger' },
            { label: 'Request more info', variant: 'secondary' },
          ]}
        >
          <CollapsibleSection title="Approval chain" badge="3 steps" defaultOpen={true}>
            <SequenceItem step={1} title="Manager approval" status="completed" />
            <SequenceItem step={2} title="Security team review" detail="Pending · assigned to Leonard Riley" status="active" />
            <SequenceItem step={3} title="IT provisioning" status="pending" isLast={true} />
          </CollapsibleSection>
        </MessageAttachment>
      </Post>

      {/* 15 — ServiceNow: IT ticket high priority */}
      <Post
        avatarSrc={avatarServicenow}
        avatarAlt="ServiceNow"
        username="ServiceNow"
        timestamp="10:18 AM"
        isBot={true}
      >
        <MessageAttachment
          title="High priority IT ticket — INC0042891"
          description="Conference room AV system in Boardroom A is not displaying from HDMI input. Executive presentation scheduled in 90 minutes."
          metrics={[
            { value: 'P2 – High', label: 'Priority' },
            { value: '1 hr 20 min', label: 'SLA remaining' },
          ]}
          fields={[
            { label: 'Category', value: 'Hardware' },
            { label: 'Assignee', value: 'Unassigned', muted: true },
            { label: 'CI', value: 'AV-BR-A-001' },
            { label: 'Impact', value: 'Multiple users' },
          ]}
        >
          <CollapsibleSection title="Activity log" badge="2 entries" defaultOpen={false}>
            <TimelineItem title="Ticket created by Reception" detail="10:16 AM · via self-service portal" />
            <TimelineItem title="Escalated to IT Support" detail="10:18 AM · auto-escalation" isLast={true} />
          </CollapsibleSection>
          <ActionBar
            select={{
              placeholder: 'Assign to technician...',
              options: [
                { value: 'arjun', label: 'Arjun Patel' },
                { value: 'david', label: 'David Liang' },
                { value: 'ethan', label: 'Ethan Brooks' },
              ],
            }}
            actions={[{ label: 'Assign & notify', variant: 'primary' }]}
          />
        </MessageAttachment>
      </Post>

      {/* 16 — GitHub: PR review requested */}
      <Post
        avatarSrc={avatarGithub}
        avatarAlt="GitHub"
        username="GitHub"
        timestamp="4:05 PM"
        isBot={true}
      >
        <MessageAttachment
          header={{ initials: 'FE', title: 'frontend / design-system', subtitle: 'Pull request #1847 · feat/token-refresh' }}
          description="Implements the new semantic token layer for v3.0 design system. Replaces hardcoded hex values across all components with CSS custom properties. Includes migration guide."
          fields={[
            { label: 'Author', value: 'Emma Novak' },
            { label: 'Base branch', value: 'main' },
            { label: 'Files changed', value: '47' },
            { label: 'Checks', value: '12 passing' },
          ]}
          fieldColumns={2}
          actions={[
            {
              label: 'Open PR',
              variant: 'primary',
              trailingIcon: <OpenInNewIcon size={16} color="currentColor" />,
            },
            { label: 'Approve', variant: 'success' },
            { label: 'Request changes', variant: 'secondary' },
          ]}
        >
          <UserList
            users={[
              { avatarSrc: userLeilaH, name: 'Leila Haddad', role: 'Engineering Manager' },
              { avatarSrc: userDariusC, name: 'Darius Cole', role: 'Product Designer' },
              { avatarSrc: userEthanB, name: 'Ethan Brooks', role: 'Backend Engineer' },
              { avatarSrc: userMarcoR, name: 'Marco Rinaldi', role: 'Security Analyst' },
              { avatarSrc: userArjunP, name: 'Arjun Patel', role: 'Platform Administrator' },
            ]}
          />
        </MessageAttachment>
      </Post>

      {/* 17 — Linear: Sprint standup summary */}
      <Post
        avatarSrc={avatarLinear}
        avatarAlt="Linear"
        username="Linear"
        timestamp="9:00 AM"
        isBot={true}
      >
        <MessageAttachment
          title="Sprint 52 — standup summary"
          description="Automated standup digest for Platform Engineering. 4 active issues across 3 engineers."
          actions={[
            {
              label: 'View sprint',
              variant: 'primary',
              trailingIcon: <OpenInNewIcon size={16} color="currentColor" />,
            },
          ]}
        >
          <CollapsibleSection title="Issue status" badge="8 issues" defaultOpen={true}>
            <SequenceItem step={1} title="Token refresh endpoint — Ethan Brooks" detail="Completed yesterday" status="completed" />
            <SequenceItem step={2} title="Design system token migration — Emma Novak" detail="In progress · PR open" status="active" />
            <SequenceItem step={3} title="CI pipeline cache optimisation — Lukas Meyer" detail="In progress · blocked on infra access" status="active" />
            <SequenceItem step={4} title="API rate limiting — Danielle Okoro" detail="Pending · starts tomorrow" status="pending" isLast={true} />
          </CollapsibleSection>
        </MessageAttachment>
      </Post>

      {/* 18 — Security: Suspicious login activity */}
      <Post
        avatarSrc={avatarPagerduty}
        avatarAlt="Security"
        username="Security"
        timestamp="7:14 AM"
        isBot={true}
      >
        <MessageAttachment
          title="Suspicious login activity detected"
          description="Multiple failed authentication attempts have been detected against a privileged account. Geographic anomaly: attempts originating from three different countries within a 12-minute window."
          metrics={[
            { value: '47', label: 'Failed attempts' },
            { value: '3', label: 'Source IPs' },
            { value: '2', label: 'Accounts targeted' },
          ]}
          fields={[
            { label: 'Target account', value: 'leonard.riley@company.com' },
            { label: 'Source IPs', value: '185.220.x.x · 91.108.x.x · 198.44.x.x' },
            { label: 'Location', value: 'Russia · Netherlands · Brazil' },
            { label: 'Time window', value: '7:01 AM – 7:13 AM' },
            { label: 'Recommended action', value: 'Immediately suspend affected accounts and rotate credentials. Block identified IP ranges at the firewall level. Initiate incident review with the security team.', colSpan: 2 },
          ]}
          fieldColumns={2}
          actions={[
            { label: 'Suspend accounts', variant: 'danger' },
            { label: 'Block IPs', variant: 'danger' },
            {
              label: 'View audit log',
              variant: 'secondary',
              trailingIcon: <OpenInNewIcon size={16} color="currentColor" />,
            },
          ]}
        />
      </Post>

      {/* 19 — Greenhouse: New candidate in pipeline */}
      <Post
        avatarSrc={avatarGreenhouse}
        avatarAlt="Greenhouse"
        username="Greenhouse"
        timestamp="2:20 PM"
        isBot={true}
      >
        <MessageAttachment
          header={{ initials: 'TW', title: 'Taylor Westbrook', subtitle: 'Senior Frontend Engineer · Engineering' }}
          fields={[
            { label: 'Stage', value: 'Technical interview' },
            { label: 'Applied', value: 'March 24, 2026' },
            { label: 'Source', value: 'LinkedIn Recruiter' },
            { label: 'Recruiter', value: 'Aiko Tan' },
            { label: 'Coordinator', value: 'Sofia Bauer' },
            { label: 'Interview panel', value: 'Emma Novak · Ethan Brooks' },
          ]}
          fieldColumns={2}
          actions={[
            {
              label: 'Open in Greenhouse',
              variant: 'primary',
              trailingIcon: <OpenInNewIcon size={16} color="currentColor" />,
            },
            { label: 'Schedule next interview', variant: 'secondary' },
          ]}
        >
          <CollapsibleSection title="Interview scorecard" badge="2 submitted" defaultOpen={false}>
            <TimelineItem title="Leila Haddad · Engineering Manager · Strong Yes" detail="Exceptional systems thinking and clear communication. Would thrive in a cross-functional role." />
            <TimelineItem title="Ethan Brooks · Backend Engineer · Yes" detail="Solid frontend fundamentals, good grasp of performance trade-offs. Minor gaps in TypeScript generics." isLast />
          </CollapsibleSection>
        </MessageAttachment>
      </Post>

      {/* 20 — Stripe: Payment failed */}
      <Post
        avatarSrc={avatarStripe}
        avatarAlt="Stripe"
        username="Stripe"
        timestamp="5:38 PM"
        isBot={true}
      >
        <MessageAttachment
          header={{
            initials: 'VC',
            title: 'Veloz Consulting Group',
            subtitle: 'Enterprise Plan · Monthly billing',
            chip: { label: 'Payment failed' },
          }}
          description="Automatic renewal charge for the Enterprise Plan failed. The card on file was declined by the issuing bank. This is the second consecutive failed attempt."
          metrics={[
            { value: '$3,499.00', label: 'Amount due' },
            { value: '2', label: 'Failed attempts' },
          ]}
          fields={[
            { label: 'Customer', value: 'Veloz Consulting Group' },
            { label: 'Payment method', value: 'Visa ···· 4821' },
            { label: 'Error code', value: 'card_declined' },
            { label: 'Last attempt', value: 'Today at 5:36 PM' },
          ]}
          fieldColumns={2}
          actions={[
            { label: 'Retry payment', variant: 'primary' },
            { label: 'Contact customer', variant: 'secondary' },
            {
              label: 'Open in Stripe',
              variant: 'secondary',
              trailingIcon: <OpenInNewIcon size={16} color="currentColor" />,
            },
          ]}
        />
      </Post>

      {/* 21 — PagerDuty: Manually trigger incident */}
      <Post
        avatarSrc={avatarPagerduty}
        avatarAlt="PagerDuty"
        username="PagerDuty"
        timestamp="9:12 AM"
        isBot={true}
      >
        <MessageAttachment title="Trigger a manual incident">
          <TextInput label="Incident title" placeholder="Brief description of the issue" />
          <Select
            label="Affected service"
            placeholder="Select a service"
            options={[
              { value: 'api-gateway', label: 'API Gateway' },
              { value: 'payments-service', label: 'Payments Service' },
              { value: 'auth-service', label: 'Auth Service' },
              { value: 'data-pipeline', label: 'Data Pipeline' },
            ]}
          />
          <div>
            <p style={{ fontSize: 12, fontWeight: 600, color: 'var(--center-channel-color)', marginBottom: 8 }}>Urgency</p>
            <div style={{ display: 'flex', gap: 16 }}>
              <Radio name="incident-urgency" defaultChecked>High</Radio>
              <Radio name="incident-urgency">Low</Radio>
            </div>
          </div>
          <Divider />
          <ActionBar actions={[
            { label: 'Trigger incident', variant: 'danger' },
            { label: 'Cancel', variant: 'secondary' },
          ]} />
        </MessageAttachment>
      </Post>

      {/* 22 — Jira: Create issue */}
      <Post
        avatarSrc={avatarJira}
        avatarAlt="Jira"
        username="Jira"
        timestamp="11:30 AM"
        isBot={true}
      >
        <MessageAttachment title="Create a Jira issue">
          <Select
            label="Project"
            placeholder="Select a project"
            options={[
              { value: 'platform', label: 'Platform Engineering' },
              { value: 'design-system', label: 'Design System' },
              { value: 'security', label: 'Security' },
              { value: 'growth', label: 'Growth' },
            ]}
          />
          <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: 8 }}>
            <Select
              label="Issue type"
              placeholder="Select type"
              options={[
                { value: 'bug', label: 'Bug' },
                { value: 'story', label: 'Story' },
                { value: 'task', label: 'Task' },
                { value: 'epic', label: 'Epic' },
              ]}
            />
            <Select
              label="Priority"
              placeholder="Select priority"
              options={[
                { value: 'highest', label: 'Highest' },
                { value: 'high', label: 'High' },
                { value: 'medium', label: 'Medium' },
                { value: 'low', label: 'Low' },
              ]}
            />
          </div>
          <TextInput label="Summary" placeholder="Short summary of the issue" />
          <Select
            label="Assignee"
            placeholder="Unassigned"
            options={[
              { value: 'emma', label: 'Emma Novak' },
              { value: 'ethan', label: 'Ethan Brooks' },
              { value: 'danielle', label: 'Danielle Okoro' },
              { value: 'lukas', label: 'Lukas Meyer' },
            ]}
          />
          <Checkbox>Notify assignee by email</Checkbox>
          <Divider />
          <ActionBar actions={[
            { label: 'Create issue', variant: 'primary' },
            { label: 'Cancel', variant: 'secondary' },
          ]} />
        </MessageAttachment>
      </Post>

      {/* 23 — Workday: Submit expense */}
      <Post
        avatarSrc={avatarWorkday}
        avatarAlt="Workday"
        username="Workday"
        timestamp="3:45 PM"
        isBot={true}
      >
        <MessageAttachment title="Submit an expense">
          <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: 8 }}>
            <TextInput label="Merchant" placeholder="e.g. Marriott San Francisco" />
            <TextInput label="Amount (USD)" placeholder="0.00" />
          </div>
          <Select
            label="Category"
            placeholder="Select a category"
            options={[
              { value: 'travel', label: 'Travel' },
              { value: 'meals', label: 'Meals & Entertainment' },
              { value: 'software', label: 'Software & Subscriptions' },
              { value: 'office', label: 'Office Supplies' },
              { value: 'other', label: 'Other' },
            ]}
          />
          <TextInput label="Notes" placeholder="Optional description or context" />
          <Divider />
          <ActionBar actions={[
            { label: 'Submit expense', variant: 'primary' },
            { label: 'Save draft', variant: 'secondary' },
          ]} />
        </MessageAttachment>
      </Post>

    </div>
  );
}
