import { useEffect } from 'react';
import { Routes, Route, useLocation } from 'react-router-dom';
import IndexPage from '@/pages/IndexPage';
import FramesPage from '@/pages/FramesPage';
import ComponentsPage from '@/pages/ComponentsPage';
import PostsPage from '@/pages/PostsPage';
import AiPostsPage from '@/pages/AiPostsPage';
import ConversationPage from '@/pages/ConversationPage';

const TITLE_PREFIX = 'Mattermost Post Block Playground';

const PAGE_TITLES: Record<string, string> = {
  '/': 'Home',
  '/frames': 'Post Samples',
  '/components': 'Components',
  '/posts': 'Autogenerated Posts',
  '/ai-posts': 'AI Agent Posts',
};

function DocumentTitle() {
  const { pathname } = useLocation();

  useEffect(() => {
    const page = PAGE_TITLES[pathname] ?? 'Home';
    document.title = `${TITLE_PREFIX} - ${page}`;
  }, [pathname]);

  return null;
}

export default function App() {
  return (
    <>
      <DocumentTitle />
      <Routes>
        <Route path="/" element={<IndexPage />} />
        <Route path="/frames" element={<FramesPage />} />
        <Route path="/components" element={<ComponentsPage />} />
        <Route path="/posts" element={<PostsPage />} />
        <Route path="/ai-posts" element={<AiPostsPage />} />
        <Route path="/conversation" element={<ConversationPage />} />
      </Routes>
    </>
  );
}
